version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: Start container
          command: |
            set -x
            cd Docker
            docker-compose up -d
      - run:
          name: Composer Install
          command: |
            set -x
            cd Docker
            docker-compose run php composer install
      - run:
          name: Copy Laravel .env
          command: |
            set -x
            cd src
            cp .env.example .env
      - run:
          name: Generate Application Key
          command: |
            set -x
            cd Docker
            docker-compose run php php artisan key:generate
      # Start Test
      - run:
          name: Run phpunit
          command: |
            set -x
            cd Docker
            docker-compose run php vendor/phpunit/phpunit/phpunit
      - run:
          name: Test Web Server
          command: |
            docker run --network container:nginx \
            appropriate/curl --retry 10 --retry-delay 1 --retry-connrefused http://localhost

  deploy-prod:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: heroku maintenance on
          command: heroku maintenance:on --app ${HEROKU_APP_NAME_PROD}
      - run:
          name: heroku deploy
          command: |
            git subtree push --prefix src https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME_PROD.git master
      - run:
          name: heroku maintenance off
          command: heroku maintenance:off --app ${HEROKU_APP_NAME_PROD}

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy-prod:
          requires:
          - build
          filters:
            branches:
              only: feat/#4_deploy_heroku
