version: '3'

services:
  php:
    container_name: php
    build: ./php
    volumes:
      - ../src:/var/www

  nginx:
    image: nginx
    container_name: nginx
    ports:
    - 80:80
    volumes:
    - ../src:/var/www
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php